import { Switch, Route } from 'react-router-dom';
import Head from 'next/head'
import Home from './Home';
import About from './About';
import Contact from './Contact';
import '../styles/globals.css'
import '../styles/variables.css'

export default function App({ Component, pageProps }) {
  return (
    <>
      <Head>
        <title>Example #1</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link href="https://fonts.googleapis.com/css2?family=Myriad+Pro:wght@100;400;500;600;700&display=swap" rel="stylesheet" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Switch>
        <Route exact path="/" component={Home} />
        <Route path="/about" component={About} />
        <Route path="/contact" component={Contact} />
      </Switch>

      <Component {...pageProps} />
    </>
  )
}
